### ISSUE TITLE
translate

### ISSUE THREAD

**Issue by dkpost3** [SebaUbuntu/Athena#1]
Hi. with your permission, I would like to translate this application into Russian, it helps a lot with the initial assembly of the device tree.
![photo_2023-06-07_14-12-21 (2)](https://github.com/SebaUbuntu/Athena/assets/42121541/01f18059-89d7-47f9-846e-b0c1b0f50c7e)

**Comment by SebaUbuntu** [comment]
Would love to setup something like crowdin
