### ISSUE TITLE
[Feature Request] An option for Amoled Black theme in the app

### ISSUE THREAD

**Issue by Username1-a** [SebaUbuntu/Athena#33]
Hi, thank you for this wonderful app

Just a suggestion, maybe you'll be interested in adding a toggle for enabling Amoled Black theme in the app in when it's in dark mode (just looks great + optionaly provides nice contrast)

In Athena version 0.1.0 you could have Black theme in the app by using Repainter app and tweaking system Monet theme, but unfortunately because of material components updates it is no longer possible in 0.2.0 and onwards

Just in case, here's how the app looked in Amoled Black theme in version 0.1.0:
![Screenshot_20240802-014939_Evolution X Launcher](https://github.com/user-attachments/assets/73c9107c-1fa9-4c6c-b9fd-6fc265b934d6)

**Comment by SebaUbuntu** [comment]
Unfortunately I cannot do anything about it
