### ISSUE TITLE
Why does the sign key change with each update?

### ISSUE THREAD

**Issue by WSTxda** [SebaUbuntu/Athena#5]
![Screenshot_2024-01-15-19-00-28-912_com miui packageinstaller](https://github.com/SebaUbuntu/Athena/assets/37253994/bc263e9a-cc37-4486-bb3b-2bad96b86986)

**Comment by SebaUbuntu** [comment]
GitHub handles the signing, I would guess there's nothing in place to store the debugging signing key between builds

**Comment by erayrafet** [comment]
This has me puzzles too.
