### ISSUE TITLE
Goat? 😂 

### ISSUE THREAD

**Issue by erayrafet** [SebaUbuntu/Athena#6]
🐐 
![Screenshot_20240124-033355](https://github.com/SebaUbuntu/Athena/assets/34194191/7bb2db76-71d2-4fae-8485-46cf16943609)

**Comment by SebaUbuntu** [comment]
https://github.com/SebaUbuntu/Athena/blob/master/app/src/main/java/dev/sebaubuntu/athena/fragments/UserFragment.kt#L66

https://developer.android.com/reference/android/os/UserManager#isUserAGoat()

Android Easter egg 🤷‍♂️
